module-invoices-product-entity
fakturogen/fakturogen-parent pull request #15
Opened 2021-01-17 19:03 UTC by rowinskidamian

you know what to do :)

2021-01-18 18:49 UTC, ewa-git approved these changes
everything looks ok:)

2021-01-24 21:55 UTC, KrzKos requested changes
We should not use primitive types. Please change double -> Double and long -> Long 

I am not sure if we should use nullable = true when it's default, and setting a name for column when it is only one word.

2021-01-24 21:55 UTC, KrzKos commented on fakturogen-invoice/src/main/java/pl/fakturogen/invoice/web/dto/ProductDTO.java
>  }
change primitive to class type

2021-01-25 08:07 UTC, KrzKos approved these changes

2021-01-26 16:29 UTC, merged