Comarch product connector
fakturogen/fakturogen-parent pull request #26
Opened 2021-03-05 19:02 UTC by rowinskidamian

Working classes to get productList and product by id from comarch api.
Please add review.

2021-03-05 21:12 UTC, KrzKos commented on fakturogen-comarch-connector/src/main/java/pl/fakturogen/comarch/connector/connectors/ComarchApiProductConnector.java
> +
In HttpConnectorUtils method httpGetById has modifier for url (url + "/" + id). It is not necessary to set two endpoints (without and with "/").

2021-03-05 21:20 UTC, KrzKos commented on fakturogen-comarch-connector/src/main/java/pl/fakturogen/comarch/connector/connectors/ComarchApiProductConnector.java
> +        Response response = httpConnectorUtils.httpGetById(getByIdEndpoint, id);
Dose it work? httpGetById(url, id) should accepts url without "/" at the end. It adds "/" and id inside the method. In your case result will be i.e https://app.erpxt.pl/api2/public/products//21340 with double "/" before 21340.

2021-03-05 21:26 UTC, KrzKos commented on fakturogen-comarch-connector/src/main/java/pl/fakturogen/comarch/connector/dto/ComarchProductDTO.java
> +@AllArgsConstructor
Can we use Lombok annotation for constructor?

2021-03-05 21:28 UTC, KrzKos requested changes
Please see my comments.

2021-03-07 11:48 UTC, ewa-git commented on fakturogen-web/src/main/java/pl/fakturogen/web/controller/rest/ProductController.java
> +    @RequestMapping("/getProductList")
Maybe in REST controllers would be nice to use @GetMapping, @PostMapping etc.

2021-03-07 11:51 UTC, ewa-git approved these changes
only small remarks

2021-03-08 18:36 UTC, merged